---
apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: ""
        tags: [{ key: "service.name", value: "service" }]
      nodeGraph:
        enabled: true